MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'bands#index'

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:index, :new]

end

MusicApp/app/models/album.rb
class Album < ApplicationRecord

  validates :title, :band_id, :year, :studio, presence: true

  belongs_to :band,
  foreign_key: :band_id,
  class_name: :Band

  has_many :tracks,
  foreign_key: :album_id,
  class_name: :Track
end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicApp/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums,
  foreign_key: :band_id,
  class_name: :Album

  has_many :tracks,
  through: :albums,
  source: :tracks
end

MusicApp/app/models/track.rb
class Track < ApplicationRecord
  validates :album_id, :title, :ord, :bonus, presence: true

  belongs_to :album,
  foreign_key: :album_id,
  class_name: :Album

  has_one :band,
  through: :album,
  source: :band

end

MusicApp/app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  validates :email, :session_token, :password_digest, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user.nil?
      return nil
    else
      return user if user.is_password?(password)
    end
    nil
  end


  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= reset_session_token!
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end



end

MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :ensure_logged_in

  def new
    @album = Album.new
    render :new
  end

  def create
    album = Album.new(album_params)
    if album.save
      redirect_to album_url(album)
    else
      redirect_to new_band_album_url(album_params[:band_id])
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def update
    album = Album.find(params[:id])
    if album.update(album_params)
      redirect_to album_url(album)
    else
      flash[:errors] = ["Invalid form submission"]
      redirect_to edit_album_url(album)
    end
  end

  def destroy
    album = Album.find(params[:id])
    album.destroy
    redirect_to band_url(album.band_id)
  end

  private

  def album_params
    params.require(:album).permit(:title, :band_id, :year, :studio)
  end
end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def ensure_logged_in
    unless logged_in?
      redirect_to root_url
    end
  end
end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :ensure_logged_in, except: [:index]
  def index
    @bands = Band.all
    render :index
  end

  def create
    band = Band.new(band_params)
    if band.save
      redirect_to band_url(band)
    else
      flash[:errors] = ["Band must have a unique name."]
      redirect_to new_band_url
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update
    band = Band.find(params[:id])
    band.update(band_params)
    if band.save
      redirect_to band_url(band)
    else
      flash[:errors] = ["Invalid name."]
      redirect_to edit_band_url(band)
    end
  end

  def destroy
    Band.find(band_params[:id]).destroy
    redirect_to bands_url
  end

private

  def band_params
    params.require(:band).permit(:name)
  end
end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :ensure_logged_in, except: [:new, :create]

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(login_params[:email], login_params[:password])
    if user.nil?
      flash[:errors] = ["incorrect email and/or password"]
      redirect_to new_session_url

    else
      login_user!(user)
      redirect_to user_url(user.id)
    end
  end

  def destroy
    session[:session_token] = nil
    redirect_to new_session_url
  end

private

  def login_params
    params.require(:login).permit(:email, :password)
  end
end

MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :ensure_logged_in
  def new
    @track = Track.new
    render :new
  end

  def edit
    @track = Track.find(params[:id])
    @album = @track.album
    render :edit
  end

  def create
    track = Track.new(track_params)
    if track.save
      redirect_to track_url(track)
    else
      flash[:errors] = ["Invalid form submission"]
      redirect_to new_album_track_url(track_params[:album_id])
    end
  end

  def update
    track = Track.find(params[:id])
    if track.update(track_params)
      redirect_to track_url(track)
    else
      flash[:errors] = ["Invalid form submission"]
      redirect_to edit_track_url(track)
    end
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def destroy
    track = Track.find(params[:id])
    track.destroy
    redirect_to album_url(track.album_id)
  end

  private

  def track_params
    params.require(:track).permit(:lyrics, :album_id, :title, :ord, :bonus, :title)
  end
end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_logged_in, except: [:new, :create]

  def new
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save
      login_user!(user)
      redirect_to user_url(user)
    else
      flash[:errors] = ["email and/or password invalid, please choose again"]
      redirect_to new_user_url
    end
  end

  def show
    render :show
  end


private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper

  def form_token
    <<-HTML.html_safe
    <input type="hidden" name="authenticity_token" value="#{form_authenticity_token}">
    HTML
  end
end

MusicApp/app/views/albums/_form.html.erb
<%= form_token %>
<label>Title
  <input type="text" name="album[title]" value="<%= album.title %>">
</label>

<label>Band Name
  <select name="album[band_id]">
      <option value="" disabled >Choose a band</option>
    <% Band.all.each do |band| %>
      <option value="<%= band.id %>" <%=band.id == album.band_id ? 'selected' : '' %> >
        <%= band.name %>
      </option>
    <% end %>
  </select>
</label>

<label>Year
  <input type="number" name="album[year]" value="<%= album.year %>">
</label>

<label>Studio
  <input type="radio" id="live_or_studio" name="album[studio]" value="true" <%= album.studio ? h('checked') : ''%>>
</label>

<label>Live
  <input type="radio" id="live_or_studio" name="album[studio]" value="false" <%= album.studio ? '' : h('checked')%>>
</label>

<input type="submit" name="" value="Submit">

</form>

MusicApp/app/views/albums/edit.html.erb
<form class="login_form" action="<%= album_url(@album) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <h1>Edit Album</h1>

  <%= render "form", album: @album, bands: @bands %>

MusicApp/app/views/albums/new.html.erb
<form class="login_form" action="<%= albums_url %>" method="post">
  <h1>Add an Album</h1>

  <%= render "form", album: @album, bands: @bands %>

MusicApp/app/views/albums/show.html.erb
<h2><%= @album.title %></h2>
<h3><%= @album.band.name %></h3>

<h3>Track Listing:</h3>

<ul>
<% @album.tracks.each do |track| %>
    <li><a href="<%= track_url(track) %>"><%= track.title %></a></li>
<% end %>
</ul>

<a href="<%= new_album_track_url(@album) %>">Add a Track</a>

MusicApp/app/views/bands/_form.html.erb
<%= form_token %>
<label>Name
  <input type="text" name="band[name]" value="<%= @band.name %>">
</label>

<input type="submit" name="" value="Submit">

</form>

MusicApp/app/views/bands/edit.html.erb
<form class="login_form" action="<%= band_url(@band) %>" method="post">
  <h1>Add a Band</h1>
  <input type="hidden" name="_method" value="patch">

  <%= render "form", album: @album %>

MusicApp/app/views/bands/index.html.erb
<ul>
<% @bands.each do |band| %>
    <li><a href="<%= band_url(band) %>"><%= band.name %></a></li>
<% end %>
</ul>

MusicApp/app/views/bands/new.html.erb
<form class="login_form" action="<%= bands_url %>" method="post">
  <h1>Add a Band</h1>

  <%= render "form" %>

MusicApp/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<p><a href="<%= new_band_album_url(@band.id)%>">Add An Album</a></p>

<ul>
  <% @band.albums.each do |album| %>
      <li><a href="<%= album_url(album) %>"><%= album.title %></a></li>
  <% end %>
</ul>

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>

      <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |err| %>
          <li><%= err %></li>
        <% end %>
      </ul>
      <% end %>
      <nav>

        <h2><a href="<%= root_url %>">THIS IS MUSIC APP</a></h2>

        <p>
      <% if current_user %>
        YOU ARE: <%= current_user.email.upcase %>.
          <form action="<%= session_url %>" method="post">
            <input type="hidden" name="_method" value="delete">
            <%= form_token %>
            <input type="submit" name="" value="LOG OUT">
          </form>
        </p>
      <% else %>
        <p><a href="<%= new_session_url %>">CLICK TO LOG IN</a></p>
      <% end %>
    </nav>
    </header>
    <main>
    <%= yield %>
  </main>
  </body>
</html>

MusicApp/app/views/tracks/_form.html.erb
<!-- TRACK CREATION/UPDATE FORM PARTIAL -->

<%= form_token %>
<label>Title
  <input type="text" name="track[title]" value="<%= track.title %>">
</label>

<label>Album Name
  <select name="track[album_id]">
      <option value="" disabled >Choose an album</option>
    <% Album.all.each do |album| %>
    <option value="<%= album.id %>" <%=album.id == track.album_id ? 'selected' : '' %> >
      <%= album.title %>
    </option>
    <% end %>
  </select>
</label>


<label>Bonus Track?
  <input type="checkbox" id="bonus_or_not" name="track[bonus]" value="true" <%= track.bonus ? h('checked') : ''%>>
</label>

<label>Track Number
  <input type="number" name="track[number]" value="<%= track.ord %>">
</label>


<label>Lyrics</label>
<textarea name="track[lyrics]" rows="8" cols="50"><%= track.lyrics %></textarea>



<input type="submit" name="" value="Submit">

</form>

MusicApp/app/views/tracks/edit.html.erb
<form class="login_form" action="<%= track_url(@track) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <h1>Edit Track</h1>

  <%= render "form", track: @track, album: @album %>

MusicApp/app/views/tracks/new.html.erb
<form class="login_form" action="<%= tracks_url %>" method="post">
  <h1>Add a Track</h1>

  <%= render "form", track: @track, album: @album %>

MusicApp/app/views/tracks/show.html.erb
<h3><%= @track.album.title %>, Track # <%= @track.ord %></h3>
<h2><%= @track.title %></h2>
<p><%= @track.bonus ? "Bonus Track" : "" %></p>

<h3>Track Lyrics:</h3>
<p><%= @track.lyrics %></p>


<a href="<%= edit_track_url(@track) %>">Edit Track</a>

MusicApp/app/views/users/new.html.erb
<form class="login_form" action="<%= users_url %>" method="post">
  <h1>Please Enter Your Email and Desired Password Below</h1>
  <%= form_token %>
  <label>Email Address
    <input type="text" name="user[email]" value="">
  </label>

  <label>Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Login">

</form>

MusicApp/app/views/users/show.html.erb
<p>Hey there, <%= current_user.email %> </p>